name: Rust

on:
  push:
    branches: [master]
    paths:
        - ".github/workflows/rust.yml"
        - "rust/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo run

    - name: Test
      run: ../test.sh
